name: Docker Image

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          network=host

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: fortawesome+robot
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: quay.io/fortawesome/phoenix-app:${{ github.event.release.tag_name }}

